using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Applications
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     An application that we can receive exceptions for.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         It can also be a specific tier in an application. For instance ASP.NET WebApi, or client side (like an Mobile
    ///         application).
    ///     </para>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}