using System.Runtime.CompilerServices;

namespace codeRR.Server.App.Core.Accounts
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    /// Accounts
    /// </summary>
    /// <remarks>
    /// <para>Accounts are used to handle authentication and site wide authorization. </para>
    /// 
    /// </remarks>
    [CompilerGenerated]
    class NamespaceDoc
    {
    }
}
