using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Feedback
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     Feedback / error description written by the user when the exception was caught.
    /// </summary>
    /// <remarks>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}