using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     Core
    /// </summary>
    /// <remarks>
    ///     <para>Core contains all basic functionality to get codeRR running. A minimal set of analysis is done here.</para>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}