using System.Runtime.CompilerServices;

namespace OneTrueError.Api.Core.Invitations
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    /// Invitations are sent on application basis. 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    [CompilerGenerated]
    class NamespaceDoc
    {
    }
}
