using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Reports
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     Reports represent the recieved exception along with all collected context information.
    /// </summary>
    /// <remarks>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}