using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Accounts
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     Account information (i.e. authentication and authorization)
    /// </summary>
    /// <remarks>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}