using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Incidents
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     All instances of the same exception are grouped together into an incident (i.e. even if the same exception is
    ///     thrown 100 000 it's still the same incident).
    /// </summary>
    /// <remarks>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}