using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Support
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    ///     Used to get support from Gauffin Interactive AB
    /// </summary>
    /// <remarks>
    /// </remarks>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}