using System.Runtime.CompilerServices;

namespace codeRR.Web.Areas.Receiver
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    /// Report receiver
    /// </summary>
    /// <remarks>
    /// <para>The main purpose of this area is to just RECEIVE reports. No analytics is made at all. This distinction is made to make sure that all reports are stored successfully, even if something else in the system is having trouble.</para>
    /// <para>The reports are later picked up by the ReportAnalyzer class library and are processed in it.</para>
    /// <hr />
    /// <para><em>This area should be considered to be stand alone and not related to anything else in the web site. It exists here just to make the installation experience easier.</em></para>
    /// 
    /// </remarks>
    [CompilerGenerated]
    class NamespaceDoc
    {
    }
}
