using System.Runtime.CompilerServices;

namespace codeRR.Server.Api.Core.Messaging.Commands
{
    // This file is Generated by the tool MarkdownToNamespaceDoc. ReadMe.md is the master.

    /// <summary>
    /// User related information (such as name, notifcation settings etc.)
    /// </summary>
    /// <remarks>
    /// <para>While accounts are for login authentication and authorization, users are for information about the individual.</para>
    /// 
    /// </remarks>
    [CompilerGenerated]
    class NamespaceDoc
    {
    }
}
